"use strict";
exports.__esModule = true;
var employee_1 = require("./employee");
var junior = new employee_1.Junior('Gosho', 20);
junior.work();
junior.work();
junior.work();
var senior = new employee_1.Senior('Ivaylo', 30);
senior.work();
senior.work();
senior.work();
var menager = new employee_1.Menager('Milen', 40);
menager.work();
menager.work();
menager.work();
